Module CargarDatosBaseAfip
    Public codSiniestrados As New RegistrarCodigosSiniestrados
    Public modoContratacion As New RegistrarModosContratacion
    Public actividadesEmpleados As New RegistrarCodigosActividadEmpleados
    Public codCondicion As New RegistrarCodigosCondicion
    Public situacionRevista As New RegistrarSituacionRevista
    Public codLocalidades As New RegistrarCodigosLocalidades
    Public codObrasSociales As New RegistrarCodigosObrasSociales
    Public formasDePago As New RegistrarFormasdePago
    Public tiposEmpresa As New RegistrarTiposEmpresa
    Public tiposConceptoSueldo As New RegistrarTiposConceptosSueldos
    Public afirmativoNegativo As New RegistrarAfirmativoNegativo

    Sub CargarAfirmativoNegativo()
        afirmativoNegativo.Add(New CodigosAfirmativoNegativo(0, "NO"))
        afirmativoNegativo.Add(New CodigosAfirmativoNegativo(1, "SI"))

    End Sub
    Sub CargarCodSiniestrados()
        codSiniestrados.Add(New CodigosSiniestrados(0, "No siniestrado"))
        codSiniestrados.Add(New CodigosSiniestrados(1, "Incapacidad Laboral Temporaria (ILT)"))
        codSiniestrados.Add(New CodigosSiniestrados(2, "Incapacidad Laboral Permanente Parcial Provisoria (ILPPP)"))
        codSiniestrados.Add(New CodigosSiniestrados(3, "Incapacidad Laboral Permanente Parcial Provisoria (ILPPD)"))
        codSiniestrados.Add(New CodigosSiniestrados(4, "Incapacidad Laboral Permanente Total Provisoria (ILPTP)"))
        codSiniestrados.Add(New CodigosSiniestrados(5, "Capital de Recomposicion. Punto 3. Articulo 15 de la Ley 24.557"))
    End Sub

    Sub CargarModosContratacion()
        modoContratacion.Add(New CodigosModosContratacion(0, "Contrato Modalidad Promovida. Reducción 0% "))
        modoContratacion.Add(New CodigosModosContratacion(1, "A tiempo parcial: Indeterminado/permanente "))
        modoContratacion.Add(New CodigosModosContratacion(2, "Becarios - Residencias médicas Ley N° 22.127"))
        modoContratacion.Add(New CodigosModosContratacion(3, "De aprendizaje Ley N° 25.013 "))
        modoContratacion.Add(New CodigosModosContratacion(4, "Especial de Fomento del Empleo Ley N° 24.465 "))
        modoContratacion.Add(New CodigosModosContratacion(5, "Fomento del Empleo Ley N° 24.013 y Ley N° 24.465 "))
        modoContratacion.Add(New CodigosModosContratacion(6, "Lanzamiento nueva actividad. Idem 005 "))
        modoContratacion.Add(New CodigosModosContratacion(7, "Período de prueba Ley N° 24.465 y Ley N° 25.013 "))
        modoContratacion.Add(New CodigosModosContratacion(8, "A Tiempo completo indeterminado/Trabajo permanente "))
        modoContratacion.Add(New CodigosModosContratacion(9, "Práctica laboral para jóvenes "))
        modoContratacion.Add(New CodigosModosContratacion(10, "Pasantías Ley N° 25.165 Decreto N° 340/92 /Pasantías - sin obra social "))
        modoContratacion.Add(New CodigosModosContratacion(11, "Trabajo de temporada "))
        modoContratacion.Add(New CodigosModosContratacion(12, "Trabajo eventual "))
        modoContratacion.Add(New CodigosModosContratacion(13, "Trabajo formación "))
        modoContratacion.Add(New CodigosModosContratacion(14, "Nuevo Período de Prueba "))
        modoContratacion.Add(New CodigosModosContratacion(15, "Puesto Nuevo Varones y Mujeres de 25 a 44 años Ley N° 25.250 "))
        modoContratacion.Add(New CodigosModosContratacion(16, "Nuevo Período de Prueba Trabajador Discapacitado Art. 34 Ley N° 24.147 "))
        modoContratacion.Add(New CodigosModosContratacion(17, "Puesto Nuevo menor de 25 años, Varones y Mujeres de 45 o más años y Mujer Jefe de familia S/límite/edad Ley 25250 "))
        modoContratacion.Add(New CodigosModosContratacion(18, "Trabajador Discapacitado Art. 34 Ley N° 24.147 "))
        modoContratacion.Add(New CodigosModosContratacion(19, "Puesto Nuevo Varones y Mujeres 25 a 44 años Art. 34 Ley N° 24.147 Ley N° 25.250 "))
        modoContratacion.Add(New CodigosModosContratacion(20, "Puesto Nuevo Menor 25 años, Varones y Mujeres 45 o más y Mujer Jefe de familia S/límite de edad. Art. 34 Ley N° 24.147 y Ley N° 25.250"))
        modoContratacion.Add(New CodigosModosContratacion(21, "A tiempo parcial determinado (contrato a plazo fijo)) "))
        modoContratacion.Add(New CodigosModosContratacion(22, "A Tiempo completo determinado (contrato a plazo fijo)) "))
        modoContratacion.Add(New CodigosModosContratacion(23, "Personal no permanente Ley N° 22.248 "))
        modoContratacion.Add(New CodigosModosContratacion(24, "Personal de la Construcción Ley N° 22.250 "))
        modoContratacion.Add(New CodigosModosContratacion(25, "Empleo público provincial "))
        modoContratacion.Add(New CodigosModosContratacion(26, "Beneficiario de programa de empleo, capacitación y de recuperación productiva "))
        modoContratacion.Add(New CodigosModosContratacion(27, "Pasantías Decreto N° 1.227/01 /Pasantías Ley N° 26.427 -con obra social28 Programas Jefes y Jefas de Hogar "))
        modoContratacion.Add(New CodigosModosContratacion(29, "Decreto N° 1.212/03 Aportante Autónomo "))
        modoContratacion.Add(New CodigosModosContratacion(30, "Nuevo Periodo de Prueba Trabajador Discapacitado Art. 87 Ley N° 24.013 "))
        modoContratacion.Add(New CodigosModosContratacion(31, "Trabajador Discapacitado Art. 87 Ley N° 24.013 "))
        modoContratacion.Add(New CodigosModosContratacion(32, "Periodo de Prueba Art. 6° Ley N° 25.877. "))
        modoContratacion.Add(New CodigosModosContratacion(33, "Periodo de Prueba Art. 6° Ley N° 25.877 Beneficiarios de planes Jefes y Jefas de hogar "))
        modoContratacion.Add(New CodigosModosContratacion(34, "Periodo de Prueba Art. 6° Ley N° 25.877. Art. 34 Ley N° 24.147 "))
        modoContratacion.Add(New CodigosModosContratacion(35, "Periodo de Prueba Art. 6° Ley N° 25.877. Art. 34. Ley N° 24.147 Beneficiarios de planes Jefes y Jefas de hogar "))
        modoContratacion.Add(New CodigosModosContratacion(36, "Periodo de Prueba Art. 6° Ley N° 25.877.Trabajador Discapacitado Art. 87 Ley N° 24.013 "))
        modoContratacion.Add(New CodigosModosContratacion(37, "Periodo de Prueba Art. 6° Ley N° 25.877. Trabajador Discapacitado Art. 87 Ley N° 24.013 Beneficiarios planes Jefes y Jefas hogar "))
        modoContratacion.Add(New CodigosModosContratacion(38, "Puesto Nuevo Art. 6° Ley N° 25.877. "))
        modoContratacion.Add(New CodigosModosContratacion(39, "Puesto Nuevo Art. 6° Ley N° 25.877. Beneficiarios de planes Jefes y Jefas de hogar "))
        modoContratacion.Add(New CodigosModosContratacion(40, "Puesto Nuevo Art. 6° Ley N° 25.877. Art. 34 Ley N° 24.147 "))
        modoContratacion.Add(New CodigosModosContratacion(41, "Puesto Nuevo Art. 6° Ley N° 25.877. Art. 34 Ley N° 24.147. Beneficiarios de planes Jefes y Jefas de hogar "))
        modoContratacion.Add(New CodigosModosContratacion(42, "Puesto Nuevo Art. 6° Ley N° 25.877.Trabajador Discapacitado Art. 87 Ley N° 24.013 "))
        modoContratacion.Add(New CodigosModosContratacion(43, "Puesto Nuevo Art. 6° Ley N° 25.877. Trabajador Discapacitado Art 87 Ley N° 24.013 Beneficiario planes Jefes y Jefas hogar "))
        modoContratacion.Add(New CodigosModosContratacion(44, "Changa Solidaria. CCT 62/75 "))
        modoContratacion.Add(New CodigosModosContratacion(45, "Personal no permanente hoteles CCT 362/03 Art. 68 inc. B "))
        modoContratacion.Add(New CodigosModosContratacion(46, "Planta transitoria Administración Pública Nacional, Provincial y/o Municipal "))
        modoContratacion.Add(New CodigosModosContratacion(47, "Representación gremial "))
        modoContratacion.Add(New CodigosModosContratacion(48, "Art.4° Ley N° 24.241Traslado temporario desde el exterior ó Conv bilaterales de Seguridad Social "))
        modoContratacion.Add(New CodigosModosContratacion(49, "Directores - empleado SA con Obra Social y LRT "))
        modoContratacion.Add(New CodigosModosContratacion(50, "Contrato Modalidad Promovida. Reducción 50% "))
        modoContratacion.Add(New CodigosModosContratacion(51, "Pasantías Ley N° 26.427 -con obra social- beneficiario pensión de discapacidad "))
        modoContratacion.Add(New CodigosModosContratacion(95, "Planes Ministerio de Trabajo "))
        modoContratacion.Add(New CodigosModosContratacion(96, "Plan Trabajo por San Luis Ley N° 5.411/03 "))
        modoContratacion.Add(New CodigosModosContratacion(97, "Programa Trabajo para jóvenes tucumanos "))
        modoContratacion.Add(New CodigosModosContratacion(98, "BONUS 2da Oportunidad "))
        modoContratacion.Add(New CodigosModosContratacion(99, "LRT (Directores SA, municipios, org, cent y descent. Emp mixt docentes privados o publicos de jurisdicciones incorporadas o no al SIJP)) "))
        modoContratacion.Add(New CodigosModosContratacion(100, "Contrato Modalidad Promovida. Reducción 100% "))
        modoContratacion.Add(New CodigosModosContratacion(102, "Personal Permanente Discontinuo con ART (para uso de la E.U.)) "))
        modoContratacion.Add(New CodigosModosContratacion(110, "Trabajo permanente prestación continua Ley N° 26.727 "))
        modoContratacion.Add(New CodigosModosContratacion(111, "Trabajo temporario Ley N° 26.727 "))
        modoContratacion.Add(New CodigosModosContratacion(112, "Trabajo permanente discontinuo Ley N° 26.727 "))
        modoContratacion.Add(New CodigosModosContratacion(113, "Trabajo por equipo o cuadrilla familiar Ley N° 26.727 "))
        modoContratacion.Add(New CodigosModosContratacion(114, "Trabajo temporario con Reducción Ley N° 26.727 "))
        modoContratacion.Add(New CodigosModosContratacion(115, "Trabajo permanente discontinuo con Reducción Ley N° 26.727 "))
        modoContratacion.Add(New CodigosModosContratacion(201, "Puesto nuevo Art. 16 Ley N° 26.476 - beneficio primeros doce meses "))
        modoContratacion.Add(New CodigosModosContratacion(202, "Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 34 Ley N° 24.147 - beneficio primeros doce meses "))
        modoContratacion.Add(New CodigosModosContratacion(203, "Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 87 Ley N° 24.013 - beneficio primeros doce meses204 Puesto nuevo Art. 16 Ley N° 26.476 meses 13 a 24 - beneficio segundo año "))
        modoContratacion.Add(New CodigosModosContratacion(205, "Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 34 Ley N° 24.147 meses 13 a 24 - beneficio segundo año206 Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 87 Ley N° 24.013 meses 13 a 24 - beneficio segundo año211 Art. 11 inc. b Ley N° 26.476 Regularización personal no registrado "))
        modoContratacion.Add(New CodigosModosContratacion(212, "Art. 11 inc. b Ley N° 26.476. Regularización personal no registrado Trabajador discapacitado Art. 34 Ley N° 24.147 "))
        modoContratacion.Add(New CodigosModosContratacion(213, "Art. 11 inc. b Ley N° 26.476. Regularización personal no registrado Trabajador discapacitado Art. 87 Ley N° 24.013 "))
        modoContratacion.Add(New CodigosModosContratacion(221, "Art. 12 Ley N° 26.476 Regularización personal no registrado "))
        modoContratacion.Add(New CodigosModosContratacion(222, "Art. 12 Ley N° 26.476 Regularización personal no registrado Trabajador discapacitado Art. 34 Ley N° 24.147 "))
        modoContratacion.Add(New CodigosModosContratacion(223, "Art. 12 Ley N° 26.476 Regularización personal no registrado trabajador discapacitado Art. 87 Ley N° 24.013 "))
        modoContratacion.Add(New CodigosModosContratacion(301, "Art. 19 Ley 26940. Tiempo indeterminado "))
        modoContratacion.Add(New CodigosModosContratacion(302, "Art. 19 Ley 26940. Trabajador discapacitado art. 34 L 24147. Tiempo indeterminado "))
        modoContratacion.Add(New CodigosModosContratacion(303, "Art. 19 Ley 26940. Trabajador discapacitado art. 87 L 24013. Tiempo indeterminado "))
        modoContratacion.Add(New CodigosModosContratacion(304, "Art. 19 Ley 26940. Tiempo parcial. Art. 92 ter LCT "))
        modoContratacion.Add(New CodigosModosContratacion(305, "Art. 19 Ley 26940. Trabajador discapacitado art. 34 L 24147. Tiempo parcial. Art. 92 ter LCT "))
        modoContratacion.Add(New CodigosModosContratacion(306, "Art. 19 Ley 26940. Trabajador discapacitado art. 87 L 24013. Tiempo parcial. Art. 92 ter LCT "))
        modoContratacion.Add(New CodigosModosContratacion(307, "Art. 24 Ley 26940. Hasta 15 empleados. Primeros 12 meses. Tiempo indeterminado "))
        modoContratacion.Add(New CodigosModosContratacion(308, "Art. 24 Ley 26940. Hasta 15 empleados. Primeros 12 meses. Tiempo indeterminado/Trabajador discapacitado art. 34 Ley 24147 "))
        modoContratacion.Add(New CodigosModosContratacion(309, "Art. 24 Ley 26940. Hasta 15 empleados. Primeros 12 meses. Tiempo indeterminado/Trabajador discapacitado art. 87 Ley 24013 "))
        modoContratacion.Add(New CodigosModosContratacion(310, "Art. 24 Ley 26940. Hasta 15 empleados. Segundos 12 meses. Tiempo indeterminado "))
        modoContratacion.Add(New CodigosModosContratacion(311, "Art. 24 Ley 26940. Hasta 15 empleados. Segundos 12 meses. Tiempo indeterminado. Trabajador discapacitado art. 34 Ley 24147 "))
        modoContratacion.Add(New CodigosModosContratacion(312, "Art. 24 Ley 26940. Hasta 15 empleados. Segundos 12 meses. Tiempo indeterminado. Trabajador discapacitado art. 87 Ley 24013 "))
        modoContratacion.Add(New CodigosModosContratacion(313, "Art. 24 Ley 26940. 16 a 80 empleados. Tiempo indeterminado "))
        modoContratacion.Add(New CodigosModosContratacion(314, "Art. 24 Ley 26940. 16 a 80 empleados. Tiempo indeterminado. Trabajador discapacitado art. 34 Ley 24147 "))
        modoContratacion.Add(New CodigosModosContratacion(315, "Art. 24 Ley 26940. 16 a 80 empleados. Tiempo indeterminado. Trabajador discapacitado art. 87 Ley 24013 "))
        modoContratacion.Add(New CodigosModosContratacion(985, "CCG Vitivinícola de Neuquén "))
        modoContratacion.Add(New CodigosModosContratacion(987, "CCG Vitivinícola de La Rioja "))
        modoContratacion.Add(New CodigosModosContratacion(989, "CCG Tabaco Salta "))
        modoContratacion.Add(New CodigosModosContratacion(990, "CCG Tabaco Jujuy "))
        modoContratacion.Add(New CodigosModosContratacion(991, "CCG Vitivinícola de Río Negro "))
        modoContratacion.Add(New CodigosModosContratacion(992, "CCG Multiproducto del Chaco "))
        modoContratacion.Add(New CodigosModosContratacion(994, "CCG Yerba Mate Misiones y Corrientes "))
        modoContratacion.Add(New CodigosModosContratacion(995, "CCG Vitivinícola de San Juan "))
        modoContratacion.Add(New CodigosModosContratacion(996, "CCG Vitivinícola de Mendoza "))
        modoContratacion.Add(New CodigosModosContratacion(997, "CCG forestal del Chaco "))
        modoContratacion.Add(New CodigosModosContratacion(998, "CCG tabaco Virginia del Chaco"))
        modoContratacion.Add(New CodigosModosContratacion(999, "Art. 11 Ley N° 26.476.Trabajador registrado. Rectificación real fecha de inicio"))
    End Sub

    Sub CargarActividadesEmpleados()
        actividadesEmpleados.Add(New CodigosActividadEmpleados(0, "Zona de Desastre. Decreto N° 1.386/01 excepto actividad agropecuaria "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(1, "Producción Primaria excepto actividad agropecuaria "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(2, "Producción de bienes sin comercialización "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(3, "Construcción de inmuebles "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(4, "Turismo "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(5, "Investigación Científica y Tecnológica "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(6, "Administración Pública. Con Obra Social Ley N° 23.660 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(7, "Enseñanza Privada Ley N° 13.047 no comprendidos en el Decreto N° 137/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(8, "Servicio Doméstico "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(9, "Servicios energéticos Res. MTESS 268 y 824/09 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(10, "Universidades privadas personal no docente Decreto N° 1.123/99 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(11, "Personal Permanente Discont. Empresas de Servicios Eventuales "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(12, "PIT - Programas Intensivos de Trabajo "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(13, "Personal embarcado "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(14, "Personal embarcado Decreto N° 1.255 S/res SSS 18/99 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(15, "L.R.T.-Directores SA, municipios, org, cent y descent. Emp mixt provin y otros16 No obligados con el SIJP (colegios, reciprocidad previsional y otros) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(17, "Obligados al SIJP-sin Obra Social Nacional (Adm Púb y otros) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(18, "Provincia incorporada al SIJP sin obra social nacional con ART "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(19, "Provincia incorporada al SIJP sin obra social nacional sin ART "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(20, "Ley N° 24.331 Zona Franca "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(21, "Decreto N° 1.024/93 Empr del Estado, Org. y Entes Públicos con OS y FNE "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(22, "Decreto N° 1.024/93 Empr del Estado, Org. y Entes Públicos sin OS y con FNE "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(27, "Servicio exterior Ley N° 22.731 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(29, "Personal embarcado Decreto N° 1.255 S/res SSS 18/99 con Obra Social "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(30, "AFA Decreto Nº 1.212/03. Aportante autônomo "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(31, "Trabajador rural de la Armada Argentina "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(32, "CSJN Corte Suprema de Justicia, Magistrados provinciales, Revisores de Cuenta "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(33, "Representante gremial en uso de licencia "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(34, "Docentes estatales nacionales. Con obra social 23660- Decreto N° 137/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(35, "Docentes estatales nacionales. Sin obra social 23660 Decreto N° 137/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(36, "Investigador científico/tecnológico estatal nacional con obra social Ley N° 23.660 Decreto N° 160/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(37, "Investigador científico/tecnológico estatal nacional sin obra social Ley N° 23.660 Decreto N° 160/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(38, "Docentes privados Res 71/99 SSS - Decreto N° 137/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(39, "No docentes privados Res 71/99 SSS "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(40, "Industria del software Ley N° 25.922 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(41, "Trabajador de la Construcción Ley 25.345 Art. 36 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(42, "Asignaciones Familiares y FNE con Obra Social Nacional "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(43, "Asignaciones Familiares y FNE sin Obra Social Nacional "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(44, "Ley N° 24061 Dto. N° 249/92 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(45, "Provincia incorporada al SIJP con obra social nacional con ART "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(46, "Provincia incorporada al SIJP con obra social nacional sin ART "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(47, "Ley N° 15.223 con obra social "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(48, "Régimen nacional sin obra social nacional "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(49, "Actividades no clasificadas "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(50, "POLICÍA DE LA RIOJA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(51, "POLICÍA DE JUJUY "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(52, "POLICÍA DE TUCUMÁN "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(53, "POLICÍA DE CATAMARCA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(54, "POLICÍA DE RÍO NEGRO "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(55, "POLICÍA DE MENDOZA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(56, "POLICÍA DE SANTIAGO DEL ESTERO "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(57, "POLICÍA DE SALTA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(58, "POLICÍA DE SAN JUAN "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(59, "POLICÍA DE SAN LUIS "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(60, "SERVICIO PENITENCIARIO DE SAN LUIS "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(61, "POLICÍA METROPOLITANA DEL GOBIERNO DE LA CIUDAD DE BUENOS AIRES "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(62, "Personal sin estado policial POLICÍA METROPOLITANA DEL GOBIERNO DE LA CIUDAD DE BUENOS AIRES "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(63, "SERVICIO PENITENCIARIO DE LA RIOJA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(64, "SERVICIO PENITENCIARIO DE JUJUY "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(65, "SERVICIO PENITENCIARIO DE TUCUMÁN "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(66, "SERVICIO PENITENCIARIO DE CATAMARCA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(67, "SERVICIO PENITENCIARIO DE RÍO NEGRO "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(68, "SERVICIO PENITENCIARIO DE MENDOZA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(69, "LEGISLADORES NACIONALES (DIPUTADOS Y SENADORES) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(70, "SERVICIO PENITENCIARIO DE SANTIAGO DEL ESTERO "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(71, "SERVICIO PENITENCIARIO DE SALTA "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(72, "SERVICIO PENITENCIARIO DE SAN JUAN "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(75, "Docente de Prov incorporada/SIJP S/obra social nacional C/ART Decreto N° 137/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(76, "Docente de Prov incorporada/SIJP S/obra social nacional S/ART Decreto N° 137/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(77, "Docente de Prov incorporada/SIJP C/obra social nacional C/ART Decreto N° 137/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(78, "Investigador científ/tecnológ/Prov incorporada/SIJP S/O.Social Nac C/ART -Decreto N° 160/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(79, "Investigador científ/tecnológ/Prov incorporada/SIJP C/O Social Nac C/ART -Decreto N° 160/05 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(81, "Funcionarios del Poder Judicial de la Nación Ley Nº 24.018 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(82, "Funcionarios del Poder Ejecutivo y otros Ley N° 24.018 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(83, "Presidente de la Nación y Vicepresidente de la Nación "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(84, "Docentes privados Res. 71/99 SSS – Dec. N° 137/05 sin Obra Social85 Magistrados provinciales, Revisores de Cuenta – docentes "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(86, "Decreto N° 1.474/2007 actividad minera "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(87, "Docentes Universitarios Nacionales con Obra Social Ley N° 26.508 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(88, "Docentes Universitarios Nacionales sin Obra Social Ley N° 26.508 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(91, "Régimen previsional propio. Obra Social Ley N° 23.660 y N° 24.714 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(92, "Res 71/99 SSS y otros "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(93, "Universidades privadas. Personal Docente D. N° 1.123/99 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(94, "Decreto N° 953/99 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(95, "Ley N°15.223 sin obra social "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(96, "Pers. Permanente Discontinuo Serv. Eventuales Alcanzados p/Dto. N° 96/99 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(97, "Trabajador Agrario. Ley N° 26.727 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(98, "Zona de Desastre Decreto N° 1.386/01. Actividad Agropecuaria Ley N° 25.191 "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(99, "Trabajador Agrario. Ley N° 26.727 (excluido Ley N° 26.727) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(100, "CSJN Corte Supr de Justicia, Magistrados provinciales, Revisores de Cta sin ART "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(101, "Magistrados provinciales, Revisores de Cta - docentes sin ART "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(106, "Administración Pública con obra social Ley N° 23.660 (con PAMI) Tipo de empleador especial "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(109, "Servicios energéticos Res. MTESS 268 y 824/09 - Províncias (Sin PAMI y sin Obra Social) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(110, "Servicios energéticos Res. MTESS 268 y 824/09 - Províncias con Obra Social "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(117, "Obligados SIJP –Sin Obra Social (Adm. Púb. y otros) sin PAMI- Tipo de empleador especial "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(901, "Poder Judicial (sin ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(902, "Poder Judicial (con ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(903, "Poder Legislativo (sin ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(904, "Poder Legislativo (con ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(905, "Empleo público en gral. (sin ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(906, "Empleo público en gral. (con ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(907, "Docente (sin ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(908, "Docente (con ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(909, "Fuerza de seguridad (sin ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(910, "Fuerza de seguridad (com ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(911, "No clasificados (sin ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(912, "No clasificados (con ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(913, "Prestadores de servicios (monotributo y/o autônomos) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(920, "No obligados al SIPA – Informativo (sin ART) "))
        actividadesEmpleados.Add(New CodigosActividadEmpleados(921, "No obligados al SIPA – Informativo (con ART) "))
    End Sub

    Sub CargarCodCondicion()
        codCondicion.Add(New CodigosCondicion(1, "Servicios Comunes. Mayor de 18 años"))
        codCondicion.Add(New CodigosCondicion(2, "jubilado "))
        codCondicion.Add(New CodigosCondicion(3, "menor "))
        codCondicion.Add(New CodigosCondicion(4, "menor anterior "))
        codCondicion.Add(New CodigosCondicion(5, "servicios diferenciados mayor de 18 años "))
        codCondicion.Add(New CodigosCondicion(6, "sin servicios reales "))
        codCondicion.Add(New CodigosCondicion(7, "medida de no innovar. servicios comunes "))
        codCondicion.Add(New CodigosCondicion(8, "medida de no innovar. servicios diferenciados "))
    End Sub

    Sub CargarSituacionRevista()
        situacionRevista.Add(New CodigoSituacionRevista(0, "Baja por fallecimiento "))
        situacionRevista.Add(New CodigoSituacionRevista(1, "Activo "))
        situacionRevista.Add(New CodigoSituacionRevista(2, "Bajas otras causales "))
        situacionRevista.Add(New CodigoSituacionRevista(3, "Activo Decreto N° 796/97"))
        situacionRevista.Add(New CodigoSituacionRevista(4, "Bajas otras causales Decreto N° 796/97 "))
        situacionRevista.Add(New CodigoSituacionRevista(5, "Licencia por maternidad "))
        situacionRevista.Add(New CodigoSituacionRevista(6, "Suspensiones otras causales"))
        situacionRevista.Add(New CodigoSituacionRevista(7, "Baja por despido "))
        situacionRevista.Add(New CodigoSituacionRevista(8, "Baja por despido Decreto N° 796/97 "))
        situacionRevista.Add(New CodigoSituacionRevista(9, "Suspendido. Art. 223 bis de la Ley N° 20.744. "))
        situacionRevista.Add(New CodigoSituacionRevista(10, "Licencia por excedencia "))
        situacionRevista.Add(New CodigoSituacionRevista(11, "Licencia por maternidad Down "))
        situacionRevista.Add(New CodigoSituacionRevista(12, "Licencia por vacaciones "))
        situacionRevista.Add(New CodigoSituacionRevista(13, "Licencia sin goce de haberes"))
        situacionRevista.Add(New CodigoSituacionRevista(14, "Reserva de puesto "))
        situacionRevista.Add(New CodigoSituacionRevista(15, "E.S.E. Cese transitorio de servicios (Art. 6°, incisos 6 y 7 del Decreto N° 342/92) "))
        situacionRevista.Add(New CodigoSituacionRevista(16, "Personal Siniestrado de terceros uso por la ART "))
        situacionRevista.Add(New CodigoSituacionRevista(17, "Reingreso por disposición judicial "))
        situacionRevista.Add(New CodigoSituacionRevista(18, "ILT (Incapacidad Laboral Transitoria) primeros DIEZ (10) días "))
        situacionRevista.Add(New CodigoSituacionRevista(19, "ILT (Incapacidad Laboral Transitoria) días ONCE (11) y siguientes"))
        situacionRevista.Add(New CodigoSituacionRevista(20, "Trabajador siniestrado en nómina de A.R.T. "))
        situacionRevista.Add(New CodigoSituacionRevista(21, "Trabajador de temporada Reserva de puesto "))
        situacionRevista.Add(New CodigoSituacionRevista(31, "Activo- Funciones en el exterior "))
        situacionRevista.Add(New CodigoSituacionRevista(32, "Licencia por paternidad "))
        situacionRevista.Add(New CodigoSituacionRevista(33, "Licencia por fuerza mayor (Art. 221 LCT) "))
        situacionRevista.Add(New CodigoSituacionRevista(42, "Empleado Eventual en Empresa Usuaria (para uso de la E.S.E.) "))
        situacionRevista.Add(New CodigoSituacionRevista(43, "Empleado eventual en EU (para uso de la ESE) mes incompleto"))
    End Sub

    Sub CargarCodLocalidades()
        codLocalidades.Add(New CodigosLocalidades(70, "Gral. Obligado - SANTA FE"))
        'codLocalidades.Add(New CodigosLocalidades(15312, "AVELLANEDA - SANTA FE"))
    End Sub

    Sub CargarCodObrasSociales()
        codObrasSociales.Add(New CodigosObrasSociales(126205, "(126205)OSECAC - DE LOS EMPLEADOS DE COMERCIO Y ACTIVIDADES CIVILES"))
        codObrasSociales.Add(New CodigosObrasSociales(119302, "(119302)OSPRERA - DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA ARGENTINA"))
        codObrasSociales.Add(New CodigosObrasSociales(1607, "(1607)SUTIAGA - DEL SINDICATO UNIDO DE TRABAJADORES DE LA INDUSTRIA DE AGUAS GASEOSAS DE LA PROVINCIA DE SANTA FE "))
        codObrasSociales.Add(New CodigosObrasSociales(400800, "(400800)OSDE - DE EJECUTIVOS Y DEL PERSONAL DE DIRECCION DE EMPRESAS"))
        codObrasSociales.Add(New CodigosObrasSociales(107206, "(107206)OSPES - DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS "))
        codObrasSociales.Add(New CodigosObrasSociales(112103, "(112103)UOM - DE LA UNION OBRERA METALURGICO DE LA REPUBLICA ARGENTINA "))
        codObrasSociales.Add(New CodigosObrasSociales(3801, "(3801)OBRA SOCIAL WITCEL"))
        codObrasSociales.Add(New CodigosObrasSociales(119500, "(119500)OSPSA - OBRA SOCIAL DEL PERSONAL DE LA SANIDAD ARGENTINA"))
        codObrasSociales.Add(New CodigosObrasSociales(401704, "(401704)OSDEPYM - OBRA SOCIAL DE EMPRESARIOS, PROFESIONALES Y MONOTRIBUTISTAS"))
        codObrasSociales.Add(New CodigosObrasSociales(127208, "(127208)OSMMEDT - OBRA SOCIAL DE MANDOS MEDIOS DE LAS TELECOMUNICACIONES Y LA RA DEL MERCOSUR"))
        codObrasSociales.Add(New CodigosObrasSociales(3207, "(3207)JERARQUICO - OBRA SOCIAL DE TRABAJADORES SOCIOS DE LA ASOCIACION MUTUAL DEL PERSONAL JERARQUICO DE BANCOS OFICIALES NACIONALES-JERARQUICOS SALUD"))
        codObrasSociales.Add(New CodigosObrasSociales(100106, "(100106)OSIAD - OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA ACEITERA, DESMOTADORA Y AFINES"))
        codObrasSociales.Add(New CodigosObrasSociales(110305, "(110305)OSPL - OBRA SOCIAL DEL PERSONAL LADRILLERO"))
        codObrasSociales.Add(New CodigosObrasSociales(103204, "(103204)OSCCPTAC - OBRA SOCIAL DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS"))
        codObrasSociales.Add(New CodigosObrasSociales(3900, "(003900)OSTVLA - OBRA SOCIAL DE TECNICOS DE VUELO DE LINEAS AEREAS"))
        codObrasSociales.Add(New CodigosObrasSociales(122906, "(122906)OSPESGA - OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS Y LAVADEROS AUTOMATICOS DE LA PROVINCIA DE SANTA FE"))
        codObrasSociales.Add(New CodigosObrasSociales(126908, "(126908)OSMEDICA - OBRA SOCIAL DE LOS MEDICOS DE LA CIUDAD DE BUENOS AIRES"))

    End Sub

    Sub CargarFormasdePago()
        formasDePago.Add(New CodigoFormasdePago(1, "EFECTIVO"))
        formasDePago.Add(New CodigoFormasdePago(2, "CHEQUE"))
        formasDePago.Add(New CodigoFormasdePago(3, "ACREDITACION"))
    End Sub

    Sub CargarTiposEmpresa()
        tiposEmpresa.Add(New CodigosTiposEmpresa(0, "Administración Pública"))
        tiposEmpresa.Add(New CodigosTiposEmpresa(1, "Decreto 814/01, Art2 Inc.B"))
        tiposEmpresa.Add(New CodigosTiposEmpresa(2, "Servicios Eventuales, Art2 Inc.B"))
        tiposEmpresa.Add(New CodigosTiposEmpresa(4, "Decreto 814/01, Art2 Inc.A"))
        tiposEmpresa.Add(New CodigosTiposEmpresa(5, "Servicios Eventuales, Art2 Inc.A"))
        tiposEmpresa.Add(New CodigosTiposEmpresa(7, "Enseñanza Privada"))
        tiposEmpresa.Add(New CodigosTiposEmpresa(8, "Decreto 1212/03 - AFA Clubes"))
    End Sub

    Sub CargarTiposConceptoSueldo()
        tiposConceptoSueldo.Add(New CodigosTiposConceptosSueldos(4, "REMUNERATIVO"))
        tiposConceptoSueldo.Add(New CodigosTiposConceptosSueldos(5, "NO REMUNERATIVO"))
        tiposConceptoSueldo.Add(New CodigosTiposConceptosSueldos(6, "DEDUCCIONES"))

    End Sub


End Module
